package src;

public class Main {
    public static void main(String[] args) {
        //OneDimensionalArrays.task1();
        //OneDimensionalArrays.task2();
        //OneDimensionalArrays.task3();
        //OneDimensionalArrays.task4();
        //OneDimensionalArrays.task5();
        //OneDimensionalArrays.task6();
        //OneDimensionalArrays.task7();
        //OneDimensionalArrays.task8();
        OneDimensionalArrays.task9();
        //OneDimensionalArrays.task10();
        //ArraysOfArrays.task1();
        //ArraysOfArrays.task2();
        //ArraysOfArrays.task3();
        //ArraysOfArrays.task4();
        //ArraysOfArrays.task5();
        //ArraysOfArrays.task6();
        //ArraysOfArrays.task7();
        //ArraysOfArrays.task8();
        //ArraysOfArrays.task9();
        //ArraysOfArrays.task10();
        //ArraysOfArrays.task11();
        //ArraysOfArrays.task12();
        //ArraysOfArrays.task13();
        //ArraysOfArrays.task14();
        //ArraysOfArrays.task15();
        //ArraysOfArrays.task16();
        //OneDimensionalArraysSorting.task1();
        //OneDimensionalArraysSorting.task2();
        //OneDimensionalArraysSorting.task3();
        //OneDimensionalArraysSorting.task4();
        //OneDimensionalArraysSorting.task5();
        //OneDimensionalArraysSorting.task6();
        //OneDimensionalArraysSorting.task7();
        //OneDimensionalArraysSorting.task8();
        //DecompositionUsingMethods.task1();
        //DecompositionUsingMethods.task2();
        //DecompositionUsingMethods.task3();
        //DecompositionUsingMethods.task4();
        //DecompositionUsingMethods.task5();
        //DecompositionUsingMethods.task6();
        //DecompositionUsingMethods.task7();
        //DecompositionUsingMethods.task8();
        //DecompositionUsingMethods.task9();
        //DecompositionUsingMethods.task10();
        //DecompositionUsingMethods.task11();
        //DecompositionUsingMethods.task12();
        //DecompositionUsingMethods.task13();
        //DecompositionUsingMethods.task14();
        //DecompositionUsingMethods.task15();
        //DecompositionUsingMethods.task16();
        DecompositionUsingMethods.task17();
    }
}
